version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
